### ISSUE TITLE
Shadows under top bar items fail to load upon login

### ISSUE THREAD

**Issue by adueppen** [theRealPadster/Mist-theme#1]
When logging into GNOME, the shadows that are supposed to be under the Activities label and the clock don't initially show up. They do appear after hovering the mouse over them. The issue doesn't affect the indicators on the right. Ubuntu version: 15.04 (affected 14.10 as well) GNOME version: 3.14 (affected 3.12 as well)

**Comment by adueppen** [comment]
![mist-bug](https://cloud.githubusercontent.com/assets/6982070/8025339/87474e9a-0d18-11e5-8b02-9d6d72381e5e.png) Top: before hovering mouse over it
Bottom: after
As can be seen here, the bug occasionally doesn't affect the clock.

**Comment by theRealPadster** [comment]
I know I've had this issue before. Can you reload the shell (ALT+F2 and run "r") and see if the issue arises again, or if reloading doesn't do anything? I'm on GNOME 3.16 and when I reload the shell it still has the shadow.

**Comment by adueppen** [comment]
When reloading the shell, the shadows stay. I do have Ubuntu set to login automatically, if that makes a difference.

**Comment by theRealPadster** [comment]
I logged out and back in, and the shadows were still there. I even rebooted to make sure. It seems the bug has been fixed as of GNOME 3.16. Thanks for bringing it to my attention, I didn't realise that it had been fixed. So I'll close the issue now, since I'm working on the 3.16 port and it's not a problem any more.
