### ISSUE TITLE
Consider making the top bar darker when there's a fullscreen window

### ISSUE THREAD

**Issue by tengwar** [theRealPadster/Mist-theme#7]
This theme is distracting if used with colorful wallpapers. This extension gets it right (when used with Adwaita): https://extensions.gnome.org/extension/885/dynamic-top-bar/

**Comment by theRealPadster** [comment]
The transparency for the top bar was intentional, I find it adds character even when maximised. Making it an option would be nice, but as far as I know it is impossible to do for a theme, as it needs more logic that can only be done by an extension.  Does my theme work with the extension or does it only work with Adwaita?
![screen](https://cloud.githubusercontent.com/assets/1565883/17457986/9f8cf666-5bd3-11e6-88b7-35f64e6acf35.png)

**Comment by tengwar** [comment]
The extension only seems to work with Adwaita - it switches the top bar between its normal color and transparent. But in your theme the normal color is also transparent. :)

**Comment by theRealPadster** [comment]
I just installed it and messed around a bit. It does appear to show the theme normally maximized, and make its modifications when nothing is maximized (which is the opposite of the behaviour we want here). I checked out the extension's javascript, and have confirmed that it does indeed require javascript to adapt the theme in such a way, so I will not incorporate this into the main theme. 

I did, however make a quick hack to reverse this behaviour. This is from the [latest version](https://github.com/AMDG2/GnomeShell_DynamicTopBar.git) off Git with my edit added. You can extract this to ~/.local/share/gnome-shell/extensions and enable it from the GNOME Tweak Tool. 

[modified-dynamicTopBar@gnomeshell.feildel.fr.zip](https://github.com/theRealPadster/Mist-theme/files/407930/modified-dynamicTopBar.gnomeshell.feildel.fr.zip)

In case you're interested, or anyone in the future (in case it needs updating), I just swapped the contents of the setSolid() and setTransparent() functions.
